// Generated by CoffeeScript 1.6.2
(function() {
  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    if (request.action === "getEstimation") {
      return $.ajax("http://localhost:3000/estimations", {
        data: {
          boardId: request.boardId,
          cardId: request.cardId,
          email: "goesmeira@gmail.com"
        },
        async: false,
        success: function(response) {
          return sendResponse({
            estimation: response
          });
        }
      });
    }
  });

}).call(this);
