// Generated by CoffeeScript 1.6.2
(function() {
  var getEstimation, saveEstimation;

  saveEstimation = function(request, sendResponse) {
    alert("aaa");
    return $.ajax("http://localhost:3000/estimations", {
      method: "post",
      data: {
        estimation: request.estimation
      },
      async: false,
      success: function(response) {
        return sendResponse({
          estimation: response
        });
      }
    });
  };

  getEstimation = function(request, sendResponse) {
    return $.ajax("http://localhost:3000/estimations", {
      data: {
        boardId: request.boardId,
        cardId: request.cardId,
        username: request.username
      },
      async: false,
      success: function(response) {
        return sendResponse({
          estimation: response
        });
      }
    });
  };

  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    switch (request.action) {
      case "getEstimation":
        return getEstimation(request, sendResponse);
      case "saveEstimation":
        return saveEstimation(request, sendResponse);
    }
  });

}).call(this);
