// Generated by CoffeeScript 1.4.0
(function() {
  var ajaxCalls, ajaxErrorAlert, app, boardPattern, boardStats, getCardsOnBoard, serverURL;

  app = window.trelloEstimationApp;

  serverURL = app.serverURL;

  ajaxCalls = app.ajaxCalls;

  ajaxErrorAlert = app.ajaxErrorAlert;

  boardPattern = /^https:\/\/trello.com\/b\/(\S+)\/(\S+)$/;

  boardStats = {
    estimates: [],
    trackings: []
  };

  getCardsOnBoard = function() {
    return ajaxCalls.push($.ajax("" + serverURL + "/estimations", {
      data: {
        board_id: app.getTargetId(boardPattern),
        member_name: app.getUsername()
      },
      success: function(response) {
        return console.log(response);
      },
      error: ajaxErrorAlert
    }));
  };

  /* App-level functions
  */


  app.boardIsOpen = function() {
    return document.URL.indexOf("trello.com/b/") >= 0;
  };

  app.loadBoard = function() {
    return getCardsOnBoard();
  };

}).call(this);
