// Generated by CoffeeScript 1.6.2
(function() {
  var cardDetailsIsOpen, createBoardEstimationButton, createCardEstimationButton, createCardEstimationModal, generateHTMLCode, loadEstimationForCurrentUser, setEstimationTime;

  setEstimationTime = function(time) {
    return $("#estimation_time").val(time);
  };

  loadEstimationForCurrentUser = function() {
    return chrome.runtime.sendMessage({
      action: "getEstimation",
      boardId: "50059cc127cbbd457b7457fd",
      cardId: "5"
    }, function(response) {
      if (response.estimation) {
        return setEstimationTime(response.estimation.time);
      }
    });
  };

  createBoardEstimationButton = function() {
    return $.ajax(chrome.extension.getURL("src/html/estimation_btn.html"), {
      dataType: 'html',
      success: function(html) {
        $(".list-card .badges").each(function() {});
        return $(this).append(html);
      }
    });
  };

  createCardEstimationModal = function() {
    return $.ajax(chrome.extension.getURL("src/html/estimation_modal.html"), {
      dataType: 'html',
      success: function(html) {
        $("body").append(html);
        return $("#estimation_dialog").dialog({
          autoOpen: false,
          modal: true
        });
      }
    });
  };

  createCardEstimationButton = function() {
    return $.ajax(chrome.extension.getURL("src/html/card_estimation_btn.html"), {
      dataType: 'html',
      success: function(html) {
        $(".other-actions").find(".clearfix").prepend(html);
        createCardEstimationModal();
        return $(".js-add-estimation-menu").on("click", function() {
          $("#estimation_dialog").dialog("open");
          return loadEstimationForCurrentUser();
        });
      }
    });
  };

  cardDetailsIsOpen = function() {
    return document.URL.indexOf("trello.com/card/") >= 0;
  };

  generateHTMLCode = function() {
    createBoardEstimationButton();
    if (cardDetailsIsOpen()) {
      return createCardEstimationButton();
    }
  };

  generateHTMLCode();

}).call(this);
