// Generated by CoffeeScript 1.4.0
(function() {

  chrome.runtime.onMessage.addListener(function(message, sender, sendResponse) {
    if (boardIsOpen()) {
      abortAjaxCalls;

      loadBoard();
    }
    if (cardDetailsIsOpen() && $(".js-add-estimation-menu").length === 0) {
      abortAjaxCalls;

      return loadCard();
    }
  });

}).call(this);
