// Generated by CoffeeScript 1.4.0
(function() {

  window.trelloEstimationApp = {
    serverURL: "https://localhost:5000",
    ajaxCalls: [],
    abortAjaxCalls: function() {
      var ajaxCall, _i, _len, _ref, _results;
      _ref = this.ajaxCalls;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        ajaxCall = _ref[_i];
        _results.push(ajaxCall.abort());
      }
      return _results;
    },
    getTargetId: function(targetPattern) {
      return document.URL.match(targetPattern)[1];
    },
    getUsername: function() {
      var beginParenthesis, endParenthesis, userFullName;
      userFullName = $.trim($(".header-member").find(".member-initials").attr("title"));
      beginParenthesis = userFullName.lastIndexOf("(");
      endParenthesis = userFullName.lastIndexOf(")");
      userFullName = userFullName.substr(beginParenthesis + 1);
      return userFullName.substr(0, userFullName.length - 1);
    }
  };

}).call(this);
